In [ ]:

import pandas as pd
import numpy as np


In [ ]:

M = [ 
    [1.000,	0.000,	1.000,	0.000,	0.000,	0.000,	1.000,	1.000,	0.000,	0.000,	0.000,	1.000,	0.667,	0.000,	0.000],
    [0.244,	0.244,	0.122,	0.244,	0.000,	0.244,	0.122,	0.244,	0.244,	0.000,	0.162,	0.162,	0.000,	0.122,	0.122],
    [0.557,	0.279,	0.279,	0.279,	0.186,	0.000,	0.000,	0.557,	0.279,	0.000,	0.000,	0.000,	0.000,	0.557,	0.557],
    [0.338,	0.169,	0.000,	0.169,	0.338,	0.338,	0.000,	0.000,	0.169,	0.338,	0.338,	0.000,	0.338,	0.338,	0.338]
]



In [20]:
M = np.array([ 
    [1.000,	0.000,	1.000,	0.000,	0.000,	0.000,	1.000,	1.000,	0.000,	0.000,	0.000,	1.000,	0.667,	0.000,	0.000],
    [0.244,	0.244,	0.122,	0.244,	0.000,	0.244,	0.122,	0.244,	0.244,	0.000,	0.162,	0.162,	0.000,	0.122,	0.122],
    [0.557,	0.279,	0.279,	0.279,	0.186,	0.000,	0.000,	0.557,	0.279,	0.000,	0.000,	0.000,	0.000,	0.557,	0.557],
    [0.338,	0.169,	0.000,	0.169,	0.338,	0.338,	0.000,	0.000,	0.169,	0.338,	0.338,	0.000,	0.338,	0.338,	0.338]
]
)

M_trans = np.array([   
    [1.   , 0.244, 0.557, 0.338],
    [0.   , 0.244, 0.279, 0.169],
    [1.   , 0.122, 0.279, 0.   ],
    [0.   , 0.244, 0.279, 0.169],
    [0.   , 0.   , 0.186, 0.338],
    [0.   , 0.244, 0.   , 0.338],
    [1.   , 0.122, 0.   , 0.   ],
    [1.   , 0.244, 0.557, 0.   ],
    [0.   , 0.244, 0.279, 0.169],
    [0.   , 0.   , 0.   , 0.338],
    [0.   , 0.162, 0.   , 0.338],
    [1.   , 0.162, 0.   , 0.   ],
    [0.667, 0.   , 0.   , 0.338],
    [0.   , 0.122, 0.557, 0.338],
    [0.   , 0.122, 0.557, 0.338]
])

# M * M^T = [

# ]


In [ ]:
M * M^T = [
    [5.444889, 0.894   , 1.393   , 0.563446],
    [0.894   , 0.46924 , 0.64599 , 0.42588 ],
    [1.393   , 0.64599 , 1.586956, 0.769119],
    [0.563446, 0.42588 , 0.769119, 0.999635]
]



In [ ]:
M^T * M = [
    [1.484029, 0.272061, 1.185171, 0.272061, 0.217846, 0.17378 , 1.029768, 1.369785, 0.272061, 0.114244, 0.153772, 1.039528, 0.781244, 0.454261, 0.454261],
    [0.272061, 0.165938, 0.107609, 0.165938, 0.109016, 0.116658, 0.029768, 0.214939, 0.165938, 0.057122, 0.09665 , 0.039528, 0.057122, 0.242293, 0.242293],
    [1.185171, 0.107609, 1.092725, 0.107609, 0.051894, 0.029768, 1.014884, 1.185171, 0.107609, 0.      , 0.019764, 1.019764, 0.667   , 0.170287, 0.170287],
    [0.272061, 0.165938, 0.107609, 0.165938, 0.109016, 0.116658, 0.029768, 0.214939, 0.165938, 0.057122, 0.09665 , 0.039528, 0.057122, 0.242293, 0.242293],
    [0.217846, 0.109016, 0.051894, 0.109016, 0.14884 , 0.114244, 0.      , 0.103602, 0.109016, 0.114244, 0.114244, 0.      , 0.114244, 0.217846, 0.217846],
    [0.17378 , 0.116658, 0.029768, 0.116658, 0.114244, 0.17378 , 0.029768, 0.059536, 0.116658, 0.114244, 0.153772, 0.039528, 0.114244, 0.144012, 0.144012],
    [1.029768, 0.029768, 1.014884, 0.029768, 0.      , 0.029768, 1.014884, 1.029768, 0.029768, 0.      , 0.019764, 1.019764, 0.667   , 0.014884, 0.014884],
    [1.369785, 0.214939, 1.185171, 0.214939, 0.103602, 0.059536, 1.029768, 1.369785, 0.214939, 0.      , 0.039528, 1.039528, 0.667   , 0.340017, 0.340017],
    [0.272061, 0.165938, 0.107609, 0.165938, 0.109016, 0.116658, 0.029768, 0.214939, 0.165938, 0.057122, 0.09665 , 0.039528, 0.057122, 0.242293, 0.242293],
    [0.114244, 0.057122, 0.      , 0.057122, 0.114244, 0.114244, 0.      , 0.      , 0.057122, 0.114244, 0.114244, 0.      , 0.114244, 0.114244, 0.114244],
    [0.153772, 0.09665 , 0.019764, 0.09665 , 0.114244, 0.153772, 0.019764, 0.039528, 0.09665 , 0.114244, 0.140488, 0.026244, 0.114244, 0.134008, 0.134008],
    [1.039528, 0.039528, 1.019764, 0.039528, 0.      , 0.039528, 1.019764, 1.039528, 0.039528, 0.      , 0.026244, 1.026244, 0.667   , 0.019764, 0.019764],
    [0.781244, 0.057122, 0.667   , 0.057122, 0.114244, 0.114244, 0.667   , 0.667   , 0.057122, 0.114244, 0.114244, 0.667   , 0.559133, 0.114244, 0.114244],
    [0.454261, 0.242293, 0.170287, 0.242293, 0.217846, 0.144012, 0.014884, 0.340017, 0.242293, 0.114244, 0.134008, 0.019764, 0.114244, 0.439377, 0.439377],
    [0.454261, 0.242293, 0.170287, 0.242293, 0.217846, 0.144012, 0.014884, 0.340017, 0.242293, 0.114244, 0.134008, 0.019764, 0.114244, 0.439377, 0.439377]
]


In [21]:
np.matmul(M, M_trans)

array([[5.444889, 0.894   , 1.393   , 0.563446],
       [0.894   , 0.46924 , 0.64599 , 0.42588 ],
       [1.393   , 0.64599 , 1.586956, 0.769119],
       [0.563446, 0.42588 , 0.769119, 0.999635]])

In [22]:
np.matmul(M_trans, M)

array([[1.484029, 0.272061, 1.185171, 0.272061, 0.217846, 0.17378 ,
        1.029768, 1.369785, 0.272061, 0.114244, 0.153772, 1.039528,
        0.781244, 0.454261, 0.454261],
       [0.272061, 0.165938, 0.107609, 0.165938, 0.109016, 0.116658,
        0.029768, 0.214939, 0.165938, 0.057122, 0.09665 , 0.039528,
        0.057122, 0.242293, 0.242293],
       [1.185171, 0.107609, 1.092725, 0.107609, 0.051894, 0.029768,
        1.014884, 1.185171, 0.107609, 0.      , 0.019764, 1.019764,
        0.667   , 0.170287, 0.170287],
       [0.272061, 0.165938, 0.107609, 0.165938, 0.109016, 0.116658,
        0.029768, 0.214939, 0.165938, 0.057122, 0.09665 , 0.039528,
        0.057122, 0.242293, 0.242293],
       [0.217846, 0.109016, 0.051894, 0.109016, 0.14884 , 0.114244,
        0.      , 0.103602, 0.109016, 0.114244, 0.114244, 0.      ,
        0.114244, 0.217846, 0.217846],
       [0.17378 , 0.116658, 0.029768, 0.116658, 0.114244, 0.17378 ,
        0.029768, 0.059536, 0.116658, 0.114244, 0.153772,

In [17]:
M.transpose()

array([[1.   , 0.244, 0.557, 0.338],
       [0.   , 0.244, 0.279, 0.169],
       [1.   , 0.122, 0.279, 0.   ],
       [0.   , 0.244, 0.279, 0.169],
       [0.   , 0.   , 0.186, 0.338],
       [0.   , 0.244, 0.   , 0.338],
       [1.   , 0.122, 0.   , 0.   ],
       [1.   , 0.244, 0.557, 0.   ],
       [0.   , 0.244, 0.279, 0.169],
       [0.   , 0.   , 0.   , 0.338],
       [0.   , 0.162, 0.   , 0.338],
       [1.   , 0.162, 0.   , 0.   ],
       [0.667, 0.   , 0.   , 0.338],
       [0.   , 0.122, 0.557, 0.338],
       [0.   , 0.122, 0.557, 0.338]])