# **A Quick Pandas Tutorial**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2023-01-05
---

> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.



---

## Prerequisite Knowledge
> Python, List, Dictionary, Tuple, Function, Lambda, Numpy, and CSV


## Agenda

**Review**
*   About a Dataset
*   Basic Numpy

**Pandas**
*   Series & Dataframe
*   Read CSV into a Pandas Dataframe
*   Column Selection
*   Row Selection
*   Row and Column Selection (1)
*   Cell Modification
*   Set Index
*   Row and Column Selection (2)
*   Reset Index
*   Range Selection
*   Conditinal Selection
*   Column Operation
*   New Column
*   Drop Row
*   Drop Column
*   Sorting
*   Grouping
*   Iteration
*   Apply Function
*   Save Dataframe into a CSV file


## About a Dataset

Click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [ ]:
pyppeteer-install

## Basic Numpy

In [2]:
[1,2,3] + [10,10,10]

[1, 2, 3, 10, 10, 10]

In [3]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
np.array([1,2,3]) + np.array([10,10,10])

array([11, 12, 13])

In [5]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(5,10,2)

array([5, 7, 9])

In [9]:
np.random.rand(5)

array([0.17959445, 0.25554576, 0.18729125, 0.86558891, 0.12378658])

In [10]:
np.random.randint(10,20,5)

array([19, 19, 14, 15, 13], dtype=int32)

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
x = np.arange(0,5)

In [14]:
x

array([0, 1, 2, 3, 4])

In [15]:
x.sum()

np.int64(10)

In [16]:
np.sum(x)

np.int64(10)

In [17]:
x.mean()

np.float64(2.0)

In [18]:
x.min()

np.int64(0)

In [19]:
x.max()

np.int64(4)

In [20]:
x.std()

np.float64(1.4142135623730951)

In [21]:
x

array([0, 1, 2, 3, 4])

In [22]:
x[2]

np.int64(2)

In [23]:
x[0:3]

array([0, 1, 2])

In [24]:
x[:3]

array([0, 1, 2])

In [25]:
x[3:]

array([3, 4])

In [26]:
x[-1]

np.int64(4)

In [27]:
x[-2]

np.int64(3)

## Pandas Series & Pandas Dataframe

In [28]:
s1 = pd.Series([0, 10, 20])

In [29]:
s1

0     0
1    10
2    20
dtype: int64

In [30]:
s1.mean()

np.float64(10.0)

In [31]:
s1.max()

np.int64(20)

In [32]:
s2 = pd.Series(["A", "B", "C"])

In [33]:
s2

0    A
1    B
2    C
dtype: object

In [34]:
df = pd.DataFrame({"name":s2, "working_years":s1})

In [35]:
df

name  working_years
0    A              0
1    B             10
2    C             20

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
type(s1)

pandas.core.series.Series

In [38]:
df["name"]

0    A
1    B
2    C
Name: name, dtype: object

In [39]:
df[["name"]]

name
0    A
1    B
2    C

In [40]:
type(df["name"])

pandas.core.series.Series

In [41]:
type(df[["name"]])

pandas.core.frame.DataFrame

## Read CSV into a Pandas Dataframe

In [42]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [43]:
df = pd.read_csv(CSV_PATH)

In [44]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [45]:
df.head()

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [46]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

## Column Selection

In [47]:
df["name"]

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [48]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [49]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

## Row Selection

In [50]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [51]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [52]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

## Row and Column Selection (1)

In [53]:
df.loc[1,["name","age"]]

name    Bordin
age         25
Name: 1, dtype: object

In [54]:
df.loc[[1], ["name","age"]]

name  age
1  Bordin   25

In [55]:
df.loc[[1,2,3], ["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [56]:
df[["name","age"]].loc[[1,2,3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [57]:
df.loc[[1,2,3]][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

## Value Modification

In [58]:
df[["name","working_years"]]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [59]:
df.loc[0,"working_years"] = 77

In [60]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [61]:
df.loc[[1,2],"working_years"] = 9999

In [62]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin           9999
2  Chantana           9999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [63]:
df.loc[[1,2],["name","working_years"]] = "MODIFIED"

C:\Users\user\AppData\Local\Temp\ipykernel_7788\2587201694.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MODIFIED' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[[1,2],["name","working_years"]] = "MODIFIED"


In [64]:
df[["name","working_years"]]

name working_years
0      Anda            77
1  MODIFIED      MODIFIED
2  MODIFIED      MODIFIED
3   Donlaya             8
4   Ekkasit             7
5    Fundee             3
6   Gitiwit             2
7     Harit             5

In [65]:
df

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             5     Bangkok

## Reload the Dataframe

In [66]:
df = pd.read_csv(CSV_PATH)

In [67]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Set Index

In [68]:
df.set_index("eid")

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [69]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [70]:
df.set_index("eid", inplace=True)

In [71]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

## Row and Column Selection (2)

In [72]:
df.loc[["E011","E012"], ["name", "salary"]]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [73]:
df.iloc[0]

name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: E011, dtype: object

In [74]:
df.iloc[[0]]

name  gender department  age   salary  working_years birth_place
eid                                                                   
E011  Anda  female  developer   39  64200.0              4     Bangkok

In [75]:
df.iloc[[0,1]]

name  gender department  age   salary  working_years birth_place
eid                                                                     
E011    Anda  female  developer   39  64200.0              4     Bangkok
E012  Bordin    male  developer   25  48700.0              2      Phuket

In [76]:
df.iloc[[0,1]][["name","gender"]]

name  gender
eid                 
E011    Anda  female
E012  Bordin    male

## Reset Index

In [77]:
df.reset_index(inplace=True)

In [78]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Reload the Dataframe



In [79]:
df = pd.read_csv(CSV_PATH)

In [80]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Range Selection

In [81]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [82]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [83]:
df.loc[4:]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [84]:
df.loc[1:3,["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [85]:
df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [86]:
df.iloc[1:4][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

## Conditional Selection

In [87]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [88]:
df[["working_years"]]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [89]:
df["working_years"]>3

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [90]:
df[df["working_years"]>3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [91]:
df[df["working_years"]>3][["name","working_years", "salary"]]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [92]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [93]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [94]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [95]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Operation

In [96]:
df["salary"]

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [97]:
df["salary"]*12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [98]:
df["salary"]*df["working_years"]

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

## New Column

In [99]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [100]:
df["country"] = "Thailand"

In [101]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  Thailand  
1  Thailand  
2  Thailand  
3  Thailand  
4  Thailand  
5  Thailand  
6  Thailand  
7  Thailand

In [102]:
df["bonus"] = df["salary"]*df["working_years"]

In [103]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

## Drop Row

In [104]:
df.drop(7)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [105]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

In [106]:
df.drop(7, inplace=True)

In [107]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [108]:
df.drop([0,1,2])

eid     name  gender department  age   salary  working_years birth_place  \
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

## Drop Column

In [109]:
df.drop("country", axis=1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

      bonus  
0  256800.0  
1   97400.0  
2  136500.0  
3  580800.0  
4  563500.0  
5  169800.0  
6   84800.0

In [110]:
df.drop(["country","bonus"], axis=1)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [111]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [112]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [113]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

## Reload the Dataframe

In [114]:
df = pd.read_csv(CSV_PATH)

In [115]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Sorting

In [116]:
df.sort_values("salary")

eid      name  gender department  age   salary  working_years birth_place
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
5  E016    Fundee  female    support   35  56600.0              3      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [117]:
df.sort_values(["department","salary"])

eid      name  gender department  age   salary  working_years birth_place
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket

In [118]:
df.sort_values("salary", ascending=False)

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [119]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [120]:
df.sort_values("salary", ascending=False, inplace=True)

In [121]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [122]:
df.loc[0:2]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [123]:
df.iloc[0:2]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Grouping

In [124]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [125]:
df.groupby("department")[['salary']].mean()

salary
department         
developer   52800.0
devops      67700.0
marketing   76550.0
support     49500.0

In [126]:
df.groupby("department").max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [127]:
df.groupby(["department","gender"]).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df.groupby(["gender","department"]).mean()

In [ ]:
df_group_obj = df.groupby("department")

In [ ]:
df_group_obj

In [ ]:
df_group_obj.mean()

In [ ]:
df_group_obj.max()

In [ ]:
df.groupby("department").min()

In [ ]:
df.groupby("department").count()

In [ ]:
df.groupby("department").agg(["mean", "count"])

In [ ]:
df.groupby("department")["age"].agg(["mean", "count"])

In [ ]:
df.groupby("department")[["age"]].agg(["mean", "count"])

In [ ]:
df.groupby("department").agg({"age":"min", "salary":"mean"})

In [ ]:
df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

In [ ]:
dfg = df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

In [ ]:
dfg

In [ ]:
dfg.columns

In [ ]:
dfg[('age','min')]

In [ ]:
dfg[[('age','min'),('salary','mean')]]

In [ ]:
dfg.columns

In [ ]:
["_".join(x) for x in dfg.columns]

In [ ]:
dfg.columns = ["_".join(x) for x in dfg.columns]

In [ ]:
dfg

In [ ]:
dfg[["age_min"]]

In [ ]:
dfg.reset_index()

In [ ]:
dfg.reset_index(inplace=True)

In [ ]:
dfg

## Reload the Dataset

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

## Iteration

In [ ]:
for index, row in df.iterrows():
  print(index)

In [ ]:
for index, row in df.iterrows():
  print(row["eid"], row["name"], row["salary"])

In [ ]:
for index, row in df.iterrows():
  #row["shoud_pay_ot"] = "Something" << is not worked
  if row["salary"]>70000:
    df.loc[index,"should_pay_ot"] = "NO"
  elif row["salary"]>50000:
    df.loc[index,"should_pay_ot"] = "MAY BE"
  else:
    df.loc[index,"should_pay_ot"] = "YES"

In [ ]:
df

## Reload the Dataset

In [ ]:
df = pd.read_csv(CSV_PATH)

## Apply Function

In [ ]:
np.log10(1000)

In [ ]:
df["salary"]

In [ ]:
df["salary"].apply(np.log10)

In [ ]:
df["salary"].apply(np.sqrt)

In [ ]:
def times10(num):
  return num*10

In [ ]:
times10(5)

In [ ]:
df["age"]

In [ ]:
df["age"].apply(times10)

In [ ]:
df["age"].apply(lambda x: x*10)

In [ ]:
def consider_ot_payment(salary):
  result = ""
  if salary>70000:
    result = "NO"
  elif salary>50000:
    result = "MAY BE"
  else:
    result = "YES"

  return result

In [ ]:
consider_ot_payment(80000)

In [ ]:
consider_ot_payment(60000)

In [ ]:
consider_ot_payment(30000)

In [ ]:
df["salary"].apply(consider_ot_payment)

In [ ]:
df["should_pay_ot"] = df["salary"].apply(consider_ot_payment)

In [ ]:
df

## Save into a CSV file

In [ ]:
df.to_csv("employee.csv")

In [ ]:
pd.read_csv("employee.csv")

In [ ]:
df.to_csv("employee1.csv", index=False)

In [ ]:
pd.read_csv("employee1.csv")



---
https://rathachai.creatier.pro/

## つづく